name: C/C++ CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - dev

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    container:
      image: ./Dockerfile
    steps:
      - name: Check code quality and vulnerabilities
        run: clang-tidy src/* -checks=google-hicpp --
